name: rayfronts
channels:
  - defaults
  - pytorch
  - nvidia
  - robostack-humble
  - conda-forge
  - pyg
dependencies:
  - python=3.11
  - pytorch
  - numpy
  - matplotlib
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pandas
  - packaging
  - scikit-image
  - opencv
  - torch-scatter
  - ros-humble-ros-base
  - ros-humble-rmw-cyclonedds-cpp
  - ros-humble-cyclonedds
  - pip
  - pip:
    - rerun-sdk
    - timm
    - segment-anything
    - einops
    - open_clip_torch
    - transformers
    - scipy
    - scikit-learn
    - hydra-core
    - nanobind
    - tqdm
